### PR TITLE
Create `!uptime`

### PR DESCRIPTION
**Pull request by bradleysigma**
image
Returns the time the bot has been online. Given as:  
- time in seconds
- time in days, hours, minutes, seconds
- time bot started

### CODE REVIEW

**Comment by nicklambourne** [comment]
There's no need to write all of this date/time nonsense yourself, please re-write using the following:

- [https://docs.python.org/3/library/datetime.html#datetime.datetime.now](https://docs.python.org/3/library/datetime.html#datetime.datetime.now)
- [https://pypi.org/project/ago/](https://pypi.org/project/ago/)

You will need to add `ago` to the setup.py dependencies.

**Review by nicklambourne — CHANGES_REQUESTED** [review]
There's no need to write all of this date/time nonsense yourself, please re-write using the following:

- [https://docs.python.org/3/library/datetime.html#datetime.datetime.now](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) `<instead of time()>`
- [https://pypi.org/project/ago/](https://pypi.org/project/ago/) `<instead of all that hand-rolled time stuff>`

You will need to add `ago` to the setup.py dependencies.

**Comment by kentonlam** [comment]
Can I also suggest a more human-friendly format? For example,

> The bot has been online 1 hour 30 minutes and 51 seconds (5451 seconds) since 12:25:16 AM November 3rd 2020.

**Comment by nicklambourne** [comment]
@bradleysigma happy to review and merge once the suggestions have been integrated.

**Comment by bradleysigma** [comment]
Updated as requested.

image

**Comment by bradleysigma** [comment]
image

**Comment by bradleysigma** [comment]
Now with ordinal suffix:
image

**Comment by bradleysigma** [comment]
Now with a single, basic test, and proper grammar: 
image

**Review by nicklambourne — APPROVED** [review]

**Pull request merged**
