### PR TITLE
Fix: Fixed bullet points for !techcrunch command

### PR DESCRIPTION
**Pull request by gaenrique**

### CODE REVIEW

**Comment by kentonlam** [comment]
Thanks for the quick fix! 

Quick formatting question: how would it look without hyphens in the heading and without blank lines between links?

**Comment by nicklambourne** [comment]
I'm with Kenton on this one, particularly on the header issue. Unless you're going to wrap the lines (so they don't exceed the length of the header) it'll probably look better without.

**Comment by nicklambourne** [comment]
You can also add a :techcrunch: logo here if you want: [https://uqcs.slack.com/customize/emoji](https://uqcs.slack.com/customize/emoji)

**Comment by gaenrique** [comment]
image

Do you guys prefer this new formatting?

**Review by nicklambourne — APPROVED** [review]

**Review by kentonlam — APPROVED** [review]

**Pull request merged**
