### PR TITLE
Added mocked API call support to testing framework

### PR DESCRIPTION
**Pull request by mitchmcdee**
This PR adds the ability for Slack API calls to be mocked and implements mocking for the `conversations.members`, `conversations.history`, `channels.list`, `groups.list`, `im.list`, `users.info` and `chat.postMessage` calls.

With this PR we can finally test our more complicated scripts and work towards complete test coverage. I have demonstrated this by fully testing `mock.py` and `welcome.py` which both rely extensively on the Slack API.

Comments and feedback much appreciated :^)

### CODE REVIEW

**Comment by TRManderson** [comment]
Can now be closed - no more async

**Comment by TRManderson** [comment]
Actually there's a lot of good non-async stuff in here

**Comment by mitchmcdee** [comment]
yeah I opened #296 to track the porting of the good shit, async stuff was minimal. Will probably keep this PR and rename it

**Comment by TRManderson** [comment]
PR needs to be retargeted to master

**Comment by mitchmcdee** [comment]
Retargeted to base branch

**Comment by mitchmcdee** [comment]
@TRManderson this PR is now ready for review if you have the time at some point (no rush <3)
@jdcaperon @nicklambourne as well if either of you would care to review (also no rush)
most of this was done when very tired so pls lemme know if something is dumb/needs further explaining

**Pull request merged**
