### PR TITLE
Adding more reacts

### PR DESCRIPTION
**Pull request by bradleysigma**
Adding more react emoji to `LOADING_REACTS`, `SUCCESS_REACTS` and `HYPE_REACTS`.

### CODE REVIEW

**Comment by jdcaperon** [comment]
lgtm :+1:

**Comment by jdcaperon** [comment]
@bradleysigma These new reacts need to be added to the uqcstesting slack.

**Comment by bradleysigma** [comment]
@jdcaperon done.

**Comment by jdcaperon** [comment]
@bradleysigma ty ty

**Pull request merged**
