### PR TITLE
Async Rate Limiting

### PR DESCRIPTION
**Pull request by TRManderson**
Uses #276 as a base, but adds more sophisticated async logic.

We could totally cheat and just use the sync method in a call to `loop.run_in_executor` but this should theoretically play nicer with our event loop?

If we'd prefer less duplication over incredibly slight perf benefits, I'll rewrite.

### CODE REVIEW

**Comment by mitchmcdee** [comment]
Would defs prefer a less duplicated version just so that we can keep core code as readable as possible

**Comment by TRManderson** [comment]
Less duplicated version pushed

**Comment by mitchmcdee** [comment]
Much better <3 does it work though? I notice no return for async?

**Comment by TRManderson** [comment]
lel I haven't tested, will fix the no return now

**Pull request merged**
