### PR TITLE
Added a passthrough system for external development

### PR DESCRIPTION
**Pull request by gricey432**
Please review. As always, I've never done node

### CODE REVIEW

**Comment by lewisjb** [comment]
The only thing that might be a problem is that the endpoints should be open source. Considering how people reacted with logging people might not be happy with not knowing what the endpoints are being used for,

**Comment by gricey432** [comment]
@lewisjb very good point, maybe it shouldn't have the user's name in it

**Comment by lewisjb** [comment]
The other thing is that currently (unless I'm mistaken) there's no way to get information back from the endpoint which **really** limits the possible functionalities

**Comment by jack775544** [comment]
We could use the Incoming Webhooks slack integration to send a message back to the chat room. We actually already have it included so we don't have to worry about going over the integration limit yet

**Comment by gricey432** [comment]
I've removed the user name but kept the unique user id, this should make it pretty much anonymous but still usable for identifying users

**Comment by gricey432** [comment]
So, what are the remaining issues with this?

**Comment by wisebaldone** [comment]
" Considering how people reacted with logging, they might not be happy with not knowing what the endpoints are being used for.". For endpoints this is a non issue since to have info "recorded" you prompt for it yourself in a command.

**Comment by lewisjb** [comment]
@wisebaldone In the current `passthroughs`, it has the pattern of `/.*/`, so *every* message that uqcsbot sees, will be sent to the endpoint. But you are right in that, if the only passthroughs have command patterns it won't be an issue.

**Comment by wisebaldone** [comment]
yep I assumed that was intended so it could be tested

**Pull request closed without merging**
