### PR TITLE
create factorial response

### PR DESCRIPTION
**Pull request by bradleysigma**
Calculates factorials. Aggressively.
image

### CODE REVIEW

**Comment by jdcaperon** [comment]
I don't see it being triggered a lot, but people will probably complain about it.

**Comment by nicklambourne** [comment]
So if I say something like "They only gave you 18!," this is going to trigger?

**Comment by bradleysigma** [comment]
Correct. Because it's more amusing this way.

**Review by kentonlam — COMMENTED** [review]
Code looks fine. I'm more worried that it'll be annoying rather than funny, particularly since it triggers automatically and on all channels.

**Comment by kumar-ish** [comment]
I also don't think it'll be triggered _too_ often but it'll mildly annoying. With that said, if you make it to be a(n im)probabilistic event (say, `if random.random() < 0.1`) I think it's fine.

**Comment by nicklambourne** [comment]
@bradleysigma I think Madhav's suggestion is good. If you set the probability at 5% or less and mock the probability for the test I'll review and merge this.

**Pull request closed without merging**
