### PR TITLE
Implement !advent command (again)

### PR DESCRIPTION
**Pull request by kentonlam**
Builds off of #397 (see there for background and discussion). Here's a [comparison](https://github.com/ldgrp/uqcsbot/compare/aoc...UQComputingSociety:aoc-2020#diff-e11d5f6a834fd09743f73a1e14aa5fe372a9eb47e9125d94148ee9bda7620998) between #397 and this branch.

- Configurable leaderboard code, year, and day via command arguments.
- Shows stars for each day in leaderboard (format copied from the [website leaderboard](https://adventofcode.com/2020/leaderboard/private/view/989288)).
- Day view which shows times per star and delta (copied from the [Chrome extension](https://chrome.google.com/webstore/detail/advent-of-code-charts/ipbomkmbokofodhhjpipflmdplipblbe?hl=en)).
- Day view can be sorted by part 1 completion time, part 2 completion time, or delta.
- Removed cron at puzzle unlock because that's a silly time to announce the leaderboard.

**To do:**
- Shuffle sort_none_last into sort_key.
- Comments and types. 
- Tests. How can these be done in a way which is independent of formatting? I'm thinking of grepping for specific ordering and times.
  **Tests are broken** and have not been updated since the original PR.
- Leaderboard is somewhat large. Attaching it as a file will allow it to be collapsed.

Screenshots:
image
image

### CODE REVIEW

**Comment by kentonlam** [comment]
More recent screenshots:
image

**Comment by nicklambourne** [comment]
jenkins retest this please

**Comment by nicklambourne** [comment]
@kentonlam I'm in the process of upgrading the bot to 3.9 so we can have literals and fix the typing errors.

**Comment by kentonlam** [comment]
I've pushed some commits which sidestep the typing problem (it should've been an enum anyway) and fixed formatting issues. 

Thanks for updating Python. Working on this PR made me realise how many quality of life features are missing from 3.6 (no dataclasses 😢).

**Comment by nicklambourne** [comment]
lol, I'd fixed most of those myself along the way, there goes that night's work 😂

**Review by nicklambourne — APPROVED** [review]

**Comment by kentonlam** [comment]
Oops, I didn't know you were working on it as well 😅

**Pull request merged**
