### PR TITLE
Reconnect if connection is dropped

### PR DESCRIPTION
**Pull request by TRManderson**
There was an error recently when the connection was dropped - this attempts a reconnection

### CODE REVIEW

**Comment by mitchmcdee** [comment]
Code has been tested?
Also, what happens if we have an exception during `connect`? Should we attempt to recover from that?

**Comment by TRManderson** [comment]
Error gets reported, no recovery is made, supervisorctl restarts process

**Comment by TRManderson** [comment]
Code has been tested but no new code paths have

**Comment by TRManderson** [comment]
Actually this is probably unnecessary now that supervisorctl is fixed

**Pull request closed without merging**
