### PR TITLE
Emoji log also includes emoji as reaction

### PR DESCRIPTION
**Pull request by bradleysigma**

### CODE REVIEW

**Comment by bradleysigma** [comment]
jenkins retest this please

**Comment by bradleysigma** [comment]
jenkins test this please

**Comment by bradleysigma** [comment]
jenkins retest this please

**Comment by bradleysigma** [comment]
jenkins add to whitelist

**Comment by bradleysigma** [comment]
jenkins retest this please

**Comment by bradleysigma** [comment]
jenkins retest this please

**Comment by bradleysigma** [comment]
jenkins retest this please

**Comment by nicklambourne** [comment]
jenkins retest this please

**Pull request merged**
