### PR TITLE
Added define command

### PR DESCRIPTION
**Pull request by mubiquity**
Adds a command that returns the dictionary definition of the argument.

define

### CODE REVIEW

**Comment by mitchmcdee** [comment]
isn't adding it as an attachment pretty much equivalent to using `>>>`? Also, would be great if you could include some tests (as per gricey's new test framework)

**Comment by mubiquity** [comment]
Using an attachment adds the grey bar which I thought was a nicer format for the response. Can change if you disagree.

Will do, forgot that was a thing now. But I will wait for another script to implement them first so I can get some idea of what is wanted.

**Comment by mitchmcdee** [comment]
image

`>>>` does that too though-- and would just make for more obvious code intention imo

as for tests, sgtm-- i'm busy for a while with uni but if you want to give it a crack i'm pretty sure gricey submitted a few examples of testing base, maybe go off that?

**Comment by mubiquity** [comment]
Oh, my bad. I see what you mean. Didn't know that piece of slack formatting.

**Comment by mubiquity** [comment]
I tried to make some tests but apparently they aren't compatible with async?

**Comment by mitchmcdee** [comment]
yeah I wrote async fixes but haven't been bothered cleaning the code yet for a PR, I'll try take a look after wednesday-- if you wanna take a look though it should be in my forked repo

**Pull request merged**
