### PR TITLE
Add test slack info to readme 

### PR DESCRIPTION
**Pull request by tgrkzus**
I've setup a test slack with 4 bot tokens for people to use. If someone else could test they can follow my instructions and get a bot connected that'd be appreciated :)

### CODE REVIEW

**Comment by mitchmcdee** [comment]
Awesome job I'll check it out in a bit :^)

**Comment by mitchmcdee** [comment]
Yep works for me, awesome :)

Small issue I saw though, gamma's token gave me delta as a bot-- maybe double check which is what :^)

**Comment by mitchmcdee** [comment]
Also, could this be baked into the run script somehow? i.e. `./bin/hubot --adapter slack -[1-4]` to give inject the tokens for you? Or is there someway to retrieve an "unused" bot by checking exit codes or something?

**Comment by tgrkzus** [comment]
Fixed the token issue.

I could probably work out a way to add it to the run script actually, I'll look into it.

**Comment by tgrkzus** [comment]
I've altered the bin/hubot script to automatically set the token env variable when provided with a number 0-3. Doesn't check if multiple people are using it so it might just explode if so.

**Comment by mitchmcdee** [comment]
Awesome :) I still think this can be improved EVEN MORE with totally automated bot getting

you can probably utilise https://api.slack.com/methods/users.getPresence to check if a bot is active, and return the first bot you can find that's not active else throw an error?

Besides being slick af, I think this would be even friendlier for new-comers

Again, I doubt we're going to have multiple people using bots such that collisions will be a huge issue-- so if you cbf doing this suggestion I understand :) It probably wouldn't be too hard though, you could even offload it to a python script for nicer handling

**Comment by tgrkzus** [comment]
I cbf. I'll do it in a later PR (maybe for hacktoberfest :))

**Pull request merged**
