### PR TITLE
Fix KeyError on missing users and update committee after 2020 SGM.

### PR DESCRIPTION
**Pull request by kentonlam**
Not sure why the KeyError problem occurs. Welcome seems to be firing correctly in the live version but did not work on testing without this change.

Apart from that, updated committee users after 2020 SGM (add Alby, James D., Paul; remove Jack, Raghav, Brian).

Also spaced out messages to show where the pauses will be between message parts.

KeyError exception below:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/__main__.py", line 2, in <module>
    main()
  File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/__init__.py", line 160, in main
    bot.run(user_token, bot_token)
  File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/base.py", line 342, in run
    run_future(self.rtm_client.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/srv/uqcsbot/lib/python3.6/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "/srv/uqcsbot/lib/python3.6/site-packages/slack/rtm/client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/base.py", line 126, in _dispatch_event
    await coro
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/api.py", line 433, in _on_user_change
    user = self._users_by_id[evt['user']['id']]
KeyError: 'U012LEHF5FX'
```

### CODE REVIEW

**Comment by TRManderson** [comment]
Can we get a corresponding change to `_on_team_join` that updates the user if it already exists?

**Comment by kentonlam** [comment]
We could, but would there be a race condition between `.get()` and updating the dict?

**Comment by TRManderson** [comment]
Good thing there's a lock easily available ;)

**Comment by kentonlam** [comment]
`_on_team_join` should be right now. I added `self._initialised = True` because it was never set, leading to rate limiting from querying the user list every `.get()`. How has the bot worked without it being set?

**Comment by TRManderson** [comment]
Given we're having trivia issues in general I'm happy for this to be merged as is given that's the failing test

**Pull request merged**
