### PR TITLE
Jobs Board Reminder

### PR DESCRIPTION
**Pull request by nicklambourne**
Weekly reminder that [link.uqcs.org/jobs](link.uqcs.org/jobs) exists.

Happy for input on the timing/frequency/content.

Screen Shot 2020-10-24 at 10 57 24 pm

### CODE REVIEW

**Review by kentonlam — APPROVED** [review]
Lgtm ❤️ 

Some small potential changes: use jobs.uqcs.org and add more emoji (:justdoit:, :flying_money_with_wings:, others?).

**Comment by nicklambourne** [comment]
Using jobs.uqcs.org now the cert is fixed. Chooses 8 random emoji from a set of 12 jobs-related ones.

Middle sentence is now a question.

**Comment by nicklambourne** [comment]
Would be nice to point the nginx endpoint for jobs.uqcs.org to link.uqcs.org/jobs so we can track clicks.

**Review by kentonlam — APPROVED** [review]
Lgtm, changes all look good 👍

**Pull request merged**
